### PR TITLE
Fix memory bug in toArray

### LINKED ISSUE #10: BUG in toArray
Did not account for the `offset` of the `ByteString` when calculating the `endPtr`.

#9 fixes this bug.

This bug causes length of the `Array` to be negative, ie. `aStart` > `aEnd` in an `Array`.

### PR DESCRIPTION
**Pull request by hasufell**

### CODE REVIEW

**Comment by adithyaov** [comment]
Thank you, @hasufell . This PR looks good to me. I'll wait till @psibi 's review and then rebase it on master.

**Review by harendra-kumar — COMMENTED** [review]
Looks good to me. 

We should add a changelog entry for the bug fix to make users aware of it. Also we should have an issue marked with a bug label and then mark it fixed in the new release, that will help users discover the bug if they encounter it and also identify the buggy releases.

**Comment by hasufell** [comment]
Note that you can also mark versions deprecated on hackage (under set preferred versions, not to be confused with deprecating the package). This should be done too.

**Comment by adithyaov** [comment]
Todos:

* [x] Bump the version to 0.1.2
* [x] Add a CHANGELOG entry
* [x] Make an Issue regarding the BUG for easy discoverability
* [x] Deprecate the previous versions

**Comment by harendra-kumar** [comment]
You can bump the version to 0.1.2 instead of 0.2.0, the latter would be a major version bump. Note that the both first and second digits are for major versions.

**Pull request merged**
