### PR TITLE
Reorder functions

### PR DESCRIPTION
**Pull request by adithyaov**

### CODE REVIEW

**Comment by adithyaov** [comment]
@psibi After this checks out I'll merge this. I also want to squash most of the commits in master to keep the history clean. I'll be force pushing to master. Please let me know if that's OK.

**Comment by psibi** [comment]
Sounds good.

**Comment by adithyaov** [comment]
@psibi Could you please take a look at the `master-fixup` branch. I'll force push that once you give me a green light.

**Comment by psibi** [comment]
@adithyaov LGTM. Can you add a small example in the README of streaming strict Bytestring from a file and possibly remove or move the TODO's to a `DEVELOPMENT.md` file ?

**Comment by adithyaov** [comment]
> Can you add a small example in the README of streaming strict Bytestring from a file and possibly remove or move the TODO's to a DEVELOPMENT.md file ?

Sure, will do.

**Comment by psibi** [comment]
Thanks @adithyaov

**Pull request merged**
