### PR TITLE
Relax upper bound on bytestring

### PR DESCRIPTION
**Pull request by jack-davies**
See discussion: https://github.com/psibi/streamly-bytestring/pull/26#issuecomment-1333083841

### CODE REVIEW

**Comment by harendra-kumar** [comment]
@adithyaov @psibi can you please approve the CIs to run.

We need to add CIs for recent versions of ghc. I think we can pick the relevant CI config from PR #26 .

**Comment by harendra-kumar** [comment]
If the checks are successful we can just upgrade the bound at Hackage and @jack-davies can pick the latest revision from Hackage.

**Comment by psibi** [comment]
>  @adithyaov @psibi can you please approve the CIs to run.

@harendra-kumar  I just added you to the repository and I believe you should have full write access from now on once you accept it.

**Comment by adithyaov** [comment]
@jack-davies 
Thanks for the PR!
Revised bounds on hackage.

**Pull request merged**
