### PR TITLE
Fix build with ghc-8.0.2 and ghc-7.10.3

### PR DESCRIPTION
**Pull request by hasufell**

### CODE REVIEW

**Comment by adithyaov** [comment]
Looks good to me. Thanks @hasufell :-)
I think we should add `ghc-8.0.2` and `ghc-7.10.3` (in general, more GHC versions) to CI.

**Comment by hasufell** [comment]
Yes, there should be another release after merging this, which then will also fix the hackage matrix: https://matrix.hackage.haskell.org/#/package/streamly-bytestring

For 0.1.0.0, you should make a [hackage revision update](https://hackage.haskell.org/package/streamly-bytestring/maintain) (change the cabal file in the online editor on hackage) to restrict building for ghc >= 8.2.

**Comment by psibi** [comment]
@hasufell Can you update the changelog and bump the version ? Thanks!

**Comment by hasufell** [comment]
> @hasufell Can you update the changelog and bump the version ? Thanks!

done

**Pull request merged**
